#!/usr/bin/env bash
# fizzbuzz script 1 to 100
i=1
while [ $i -ne 101 ]
do
	if ! ((i%15))
	then
		echo FizzBuzz
	elif ! ((i%3))
	then
		echo Fizz
	elif ! ((i%5))
	then
		echo Buzz
	else
		echo $i
	fi
	(( i+=1 ))
done
