#!/usr/bin/env bash
# Display "Holberton School" 10 times using while loop
# at the 9nth iteration display Hi
i=0
while [ $i -ne 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Holberton School"
	(( i += 1 ))
done
