#!/usr/bin/env bash
# Display numbers 1 to 20 and superstitious numbers
i=1
while [ $i -ne 21 ]
do
	case $i in 
		5)
		echo "bad luck from China" ;;
		10)
		echo "bad luck from Japan" ;;
		18)
		echo "bad luck from Italy" ;;
	esac
	echo $i
	(( i += 1 ))
done
