#!/usr/bin/env bash
# Display numbers 1 to 20 and superstitious numbers
i=1
while [ $i -ne 21 ]
do
	if [ $i -eq 5 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 10 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 18 ]
	then
		echo "bad luck from Italy"
	fi
	echo $i
	(( i += 1 ))
done
